title: <p align="center"> Dr. Parul Shah </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/dr-parul-shah-042a2819/">LinkedIn</a> |
  <a href="https://github.com/DrParulShah">GitHub</a>
  
  
  
  <br>   
  'What you do should not define who you are. Who you are should define what you do' - Sadhguru
  A firm believer of this adage, I continue to be a student even after three decades of work experience, continuously seeking knowledge from the dynamic evolution of technology in all walks of life.
  Technology excites me and challenges drive me. 
  My journey with Machine Learning and Data Science started long before I realised that I am a Data Scientist.
  <br>
  </p>










theme: jekyll-theme-minimal
